version: '1.0'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "myDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"


  app:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/myDb
    image: 'codeexample'
    ports:
      - 8091:8091
    depends_on:
      - postgres